### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by PeterJCLaw** [fables-tales/badger-vagrant#1]
The server doesn't start properly on windows:

```
[default] Running provisioner: Vagrant::Provisioners::Shell...
bash: /tmp/vagrant-shell: /bin/bash^M: bad interpreter: No such file or directory
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod +x /tmp/vagrant-shell && /tmp/vagrant-shell
```

I'm assuming that this is an issue in your stuff, as it seems odd that vagrant would be generally broken?

**Comment by fables-tales** [comment]
Someone got it to work in windows. It's probably to do with your configuration.

**Comment by tvlooy** [comment]
https://github.com/mitchellh/vagrant/issues/1181

**Comment by PeterJCLaw** [comment]
It turns out that the issue was that the build.sh file included in this repo assumes that the user will check it out onto a *nix platform. On windows, there's a reasonable chance that the user might have autocrlf set, which will make its line endings \r\n, rather than the expected \n.

The fix is to add a .gitattributes file that forces it to use \n only.
