### ISSUE TITLE
/srv/secrets is not 0700

### ISSUE THREAD

**Issue by cjsoftuk** [fables-tales/badger-vagrant#3]
/srv/secrets on badger is 0700, this is not the case in vagrant (0755), and hence causes things to fail on badger when they don't on vagrant badgers.

**Comment by fables-tales** [comment]
Send patches to srobo-puppet this is def not something badger-vagrant should special case.

**Comment by jmorse** [comment]
/srv/secrets is not deployed by puppet; it's expected to be there before puppet is ever run, so that configuration can be read out of it. Seeing how badger-vagrant is what deploys /srv/secrets, that's where that mode should be set.

To be fair, this fact isn't documented anywhere.

**Comment by fables-tales** [comment]
We could quite happily modify the repo's permissions even though it's already created when puppet is started. This would also then codify and document the permissions /srv/secrets is supposed to have.

**Comment by jmorse** [comment]
This removes the flexibility of possible testing configurations where users want /srv/secrets to possess some other mode or ownership, as required by whatever scenario they're testing. Having vagrant construct the VM according to the default configuration will allow for this. Would you like a patch?

**Comment by fables-tales** [comment]
That'd be nice, I'm currently full steam @nemesis

## Thanks

Sam Phippen

**Comment by nemesis** [comment]
Hello!
Strange, I don't remember participating in this conversation. Did you tag me by mistake?
